FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /usr/app/
# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

RUN apt update \
    && apt install --no-install-recommends -y curl \
        fonts-liberation \
        gconf-service \
        libappindicator1 \
        libasound2 \
        libatk1.0-0 \
        libcairo2 \
        libcups2 \
        libfontconfig1 \
        libgbm-dev \
        libgdk-pixbuf2.0-0 \
        libgtk-3-0 \
        libicu-dev \
        libjpeg-dev \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libpng-dev \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        xdg-utils \
        ca-certificates \
    && curl -sL https://deb.nodesource.com/setup_18.x | bash - \
    && apt install -y nodejs \
    && npm install -g npm \
    && rm -rf /var/lib/apt/lists/*

COPY ./ ./

RUN rm -rf ./node_modules \
    && npm install \
    && npm run front:build \
    && npm run back:build

ENTRYPOINT ["/usr/app/script/api-server.sh"]
