// This file is automatically generated.
// Please do not change this file!
interface CssExports {
    "storybook-button": string;
    "storybook-button--large": string;
    "storybook-button--medium": string;
    "storybook-button--primary": string;
    "storybook-button--secondary": string;
    "storybook-button--small": string;
}
export const cssExports: CssExports;
export default cssExports;
